### ISSUE TITLE
representing time and date

### ISSUE THREAD

**Issue by keski** [keski/ice-hockey-ontology#17]
This ticket is about making it more straightforward to add time concepts.

Currently we use the time ontology for this, but even though it introduces a lot of classes and properties, we still cannot attach a single timestamp or date to something without also defining new properties (e.g. attach a date to a game). I'd suggest that we simply skip the time ontology altogether and introduce the few predicates needed for out use-case, where we link to XSD datatypes. Specifically, I would like to add:

- hasDate (range: xsd:date)
- hasTime (range: xsd:datetime)
- hasStartTime (range: xsd:datetime)
- hasEndTime (range: xsd:datetime)

 If you agree, I can push this change. If not, let's continue the discussion in this issue.

@chengsijin0817 @huanyu-li

**Comment by huanyu-li** [comment]
Yes, I agree with skip the time ontology, then just define the few predicates for our use cases.
/Huanyu

On May 31, 2019, at 12:12 PM, Robin Keskisärkkä <notifications@github.com<mailto:notifications@github.com>> wrote:


This ticket is about making it more straightforward to add time concepts.

Currently we use the time ontology for this, but even though it introduces a lot of classes and properties, we still cannot attach a single timestamp or date to something without also defining new properties (e.g. attach a date to a game). I'd suggest that we simply skip the time ontology altogether and introduce the few predicates needed for out use-case, where we link to XSD datatypes. Specifically, I would like to add:

  *   hasDate (range: xsd:date)
  *   hasTime (range: xsd:datetime)
  *   hasStartTime (range: xsd:datetime)
  *   hasEndTime (range: xsd:datetime)

If you agree, I can push this change. If not, let's continue the discussion in this issue.

@chengsijin0817<https://github.com/chengsijin0817> @huanyu-li<https://github.com/huanyu-li>

**Comment by sijincheng** [comment]
Sorry, I forgot to reply to this issue.
Yes, I agree. Please push this change.
@keski
