### ISSUE TITLE
add features about location on ice

### ISSUE THREAD

**Issue by keski** [keski/ice-hockey-ontology#4]
Add ontology concepts based on the discussion and picture about location of players, face-offs, puck, zones etc. on the ice.

Alson provide illustration and description.

**Comment by huanyu-li** [comment]
![ice-hockey-zone](https://user-images.githubusercontent.com/24544813/59197125-c5b47400-8b90-11e9-96ba-66c74505eaa4.png)

**Comment by huanyu-li** [comment]
![ice-hockey-rink-2](https://user-images.githubusercontent.com/24544813/59254980-812ce500-8c31-11e9-8536-a7197cbcffad.png)
